/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fGhgcshXMvT
 */
import { CardContent, Card } from "@/components/ui/card"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"
import Image from "next/image"

export function ProductCarousel() {
  return (
    <Carousel className="w-full max-w-xs">
      <CarouselContent>
        <CarouselItem>
          <div className="p-1">
            <Card>
              <CardContent className="p-6 flex flex-col items-center gap-4">
                <Image
                  alt="Golf club"
                  className="aspect-square object-cover rounded-lg overflow-hidden"
                  height="200"
                  src="/placeholder.svg"
                  width="200"
                />
                <div className="text-sm font-medium leading-none w-full text-center">Iron Golf Club</div>
                <div className="text-sm font-medium leading-none">$149.99</div>
              </CardContent>
            </Card>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="p-1">
            <Card>
              <CardContent className="p-6 flex flex-col items-center gap-4">
                <Image
                  alt="Golf balls"
                  className="aspect-square object-cover rounded-lg overflow-hidden"
                  height="200"
                  src="/placeholder.svg"
                  width="200"
                />
                <div className="text-sm font-medium leading-none w-full text-center">Golf Balls (12-pack)</div>
                <div className="text-sm font-medium leading-none">$29.99</div>
              </CardContent>
            </Card>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="p-1">
            <Card>
              <CardContent className="p-6 flex flex-col items-center gap-4">
                <Image
                  alt="Golf accessory"
                  className="aspect-square object-cover rounded-lg overflow-hidden"
                  height="200"
                  src="/placeholder.svg"
                  width="200"
                />
                <div className="text-sm font-medium leading-none w-full text-center">Golf Cart Accessory Holder</div>
                <div className="text-sm font-medium leading-none">$19.99</div>
              </CardContent>
            </Card>
          </div>
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious />
      <CarouselNext />
    </Carousel>
  )
}
