/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8Py1suNQYgu
 */

import { Post } from "@/types/post";
import Image from "next/image";

export function PostHeader({ data }: { data: Post["data"] }) {
  return (
    <header className="overflow-hidden">
      <Image
        alt="Cover image"
        className="aspect-video object-cover"
        height={400}
        src={data.coverImage}
        width={1400}
      />
      <div className="flex flex-col space-x-4 my-4 gap-4">
        <div className="grid gap-1.5">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl lg:text-5xl">
            {data.title}
          </h1>
        </div>
        <div className="flex items-center space-x-2">
          <Image
            alt="Avatar"
            className="rounded-full"
            height={40}
            src={data.author.picture}
            style={{
              aspectRatio: "40/40",
              objectFit: "cover",
            }}
            width={40}
          />
          <div className="text-right">
            <h3 className="text-sm font-bold tracking-tight">
              {data.author.name}
            </h3>
            <p className="text-xs text-gray-500 dark:text-gray-400">
              {new Date(data.date).toLocaleDateString("en-US", {
                year: "numeric",
                month: "long",
                day: "numeric",
              })}
            </p>
          </div>
        </div>
      </div>
    </header>
  );
}
